REM INSERTING into PAIS
SET DEFINE OFF;
Insert into PAIS (PAIS_ID,NOMBRE) values ('PYF','Polinesia Francesa');
Insert into PAIS (PAIS_ID,NOMBRE) values ('BGR','Bulgaria');
Insert into PAIS (PAIS_ID,NOMBRE) values ('BFA','Burkina Faso');
Insert into PAIS (PAIS_ID,NOMBRE) values ('BDI','Burundi');
Insert into PAIS (PAIS_ID,NOMBRE) values ('CPV','Cabo Verde');
Insert into PAIS (PAIS_ID,NOMBRE) values ('KHM','Camboya');
Insert into PAIS (PAIS_ID,NOMBRE) values ('CMR','Camerún');
Insert into PAIS (PAIS_ID,NOMBRE) values ('CAN','Canadá');
Insert into PAIS (PAIS_ID,NOMBRE) values ('TCD','Chad');
Insert into PAIS (PAIS_ID,NOMBRE) values ('CHL','Chile');
Insert into PAIS (PAIS_ID,NOMBRE) values ('CHN','China');
Insert into PAIS (PAIS_ID,NOMBRE) values ('CYP','Chipre');
Insert into PAIS (PAIS_ID,NOMBRE) values ('VAT','Ciudad del Vaticano');
Insert into PAIS (PAIS_ID,NOMBRE) values ('COL','Colombia');
Insert into PAIS (PAIS_ID,NOMBRE) values ('COM','Comoras');
Insert into PAIS (PAIS_ID,NOMBRE) values ('COG','Congo');
Insert into PAIS (PAIS_ID,NOMBRE) values ('COD','Congo');
Insert into PAIS (PAIS_ID,NOMBRE) values ('PRK','Corea del Norte');
Insert into PAIS (PAIS_ID,NOMBRE) values ('KOR','Corea del Sur');
Insert into PAIS (PAIS_ID,NOMBRE) values ('CIV','Costa de Marfil');
Insert into PAIS (PAIS_ID,NOMBRE) values ('CRI','Costa Rica');
Insert into PAIS (PAIS_ID,NOMBRE) values ('HRV','Croacia');
Insert into PAIS (PAIS_ID,NOMBRE) values ('CUB','Cuba');
Insert into PAIS (PAIS_ID,NOMBRE) values ('DNK','Dinamarca');
Insert into PAIS (PAIS_ID,NOMBRE) values ('DMA','Dominica');
Insert into PAIS (PAIS_ID,NOMBRE) values ('ECU','Ecuador');
Insert into PAIS (PAIS_ID,NOMBRE) values ('EGY','Egipto');
Insert into PAIS (PAIS_ID,NOMBRE) values ('SLV','El Salvador');
Insert into PAIS (PAIS_ID,NOMBRE) values ('ARE','Emiratos Árabes Unidos');
Insert into PAIS (PAIS_ID,NOMBRE) values ('ERI','Eritrea');
Insert into PAIS (PAIS_ID,NOMBRE) values ('SVK','Eslovaquia');
Insert into PAIS (PAIS_ID,NOMBRE) values ('SVN','Eslovenia');
Insert into PAIS (PAIS_ID,NOMBRE) values ('ESP','España');
Insert into PAIS (PAIS_ID,NOMBRE) values ('USA','Estados Unidos de América');
Insert into PAIS (PAIS_ID,NOMBRE) values ('EST','Estonia');
Insert into PAIS (PAIS_ID,NOMBRE) values ('ETH','Etiopía');
Insert into PAIS (PAIS_ID,NOMBRE) values ('PHL','Filipinas');
Insert into PAIS (PAIS_ID,NOMBRE) values ('FIN','Finlandia');
Insert into PAIS (PAIS_ID,NOMBRE) values ('FJI','Fiyi');
Insert into PAIS (PAIS_ID,NOMBRE) values ('FRA','Francia');
Insert into PAIS (PAIS_ID,NOMBRE) values ('GAB','Gabón');
Insert into PAIS (PAIS_ID,NOMBRE) values ('GMB','Gambia');
Insert into PAIS (PAIS_ID,NOMBRE) values ('GEO','Georgia');
Insert into PAIS (PAIS_ID,NOMBRE) values ('GHA','Ghana');
Insert into PAIS (PAIS_ID,NOMBRE) values ('GIB','Gibraltar');
Insert into PAIS (PAIS_ID,NOMBRE) values ('GRD','Granada');
Insert into PAIS (PAIS_ID,NOMBRE) values ('GRC','Grecia');
Insert into PAIS (PAIS_ID,NOMBRE) values ('GRL','Groenlandia');
Insert into PAIS (PAIS_ID,NOMBRE) values ('GLP','Guadalupe');
Insert into PAIS (PAIS_ID,NOMBRE) values ('GUM','Guam');
Insert into PAIS (PAIS_ID,NOMBRE) values ('GTM','Guatemala');
Insert into PAIS (PAIS_ID,NOMBRE) values ('GUF','Guayana Francesa');
Insert into PAIS (PAIS_ID,NOMBRE) values ('GGY','Guernsey');
Insert into PAIS (PAIS_ID,NOMBRE) values ('GIN','Guinea');
Insert into PAIS (PAIS_ID,NOMBRE) values ('GNQ','Guinea Ecuatorial');
Insert into PAIS (PAIS_ID,NOMBRE) values ('GNB','Guinea-Bissau');
Insert into PAIS (PAIS_ID,NOMBRE) values ('GUY','Guyana');
Insert into PAIS (PAIS_ID,NOMBRE) values ('HTI','Haití');
Insert into PAIS (PAIS_ID,NOMBRE) values ('HND','Honduras');
Insert into PAIS (PAIS_ID,NOMBRE) values ('HKG','Hong kong');
Insert into PAIS (PAIS_ID,NOMBRE) values ('HUN','Hungría');
Insert into PAIS (PAIS_ID,NOMBRE) values ('IND','India');
Insert into PAIS (PAIS_ID,NOMBRE) values ('IDN','Indonesia');
Insert into PAIS (PAIS_ID,NOMBRE) values ('IRN','Irán');
Insert into PAIS (PAIS_ID,NOMBRE) values ('IRQ','Irak');
Insert into PAIS (PAIS_ID,NOMBRE) values ('IRL','Irlanda');
Insert into PAIS (PAIS_ID,NOMBRE) values ('BVT','Isla Bouvet');
Insert into PAIS (PAIS_ID,NOMBRE) values ('IMN','Isla de Man');
Insert into PAIS (PAIS_ID,NOMBRE) values ('CXR','Isla de Navidad');
Insert into PAIS (PAIS_ID,NOMBRE) values ('NFK','Isla Norfolk');
Insert into PAIS (PAIS_ID,NOMBRE) values ('ISL','Islandia');
Insert into PAIS (PAIS_ID,NOMBRE) values ('BMU','Islas Bermudas');
Insert into PAIS (PAIS_ID,NOMBRE) values ('CYM','Islas Caimán');
Insert into PAIS (PAIS_ID,NOMBRE) values ('CCK','Islas Cocos (Keeling)');
Insert into PAIS (PAIS_ID,NOMBRE) values ('COK','Islas Cook');
Insert into PAIS (PAIS_ID,NOMBRE) values ('ALA','Islas de Åland');
Insert into PAIS (PAIS_ID,NOMBRE) values ('FRO','Islas Feroe');
Insert into PAIS (PAIS_ID,NOMBRE) values ('SGS','Islas Georgias del Sur y Sandwich del Sur');
Insert into PAIS (PAIS_ID,NOMBRE) values ('HMD','Islas Heard y McDonald');
Insert into PAIS (PAIS_ID,NOMBRE) values ('MDV','Islas Maldivas');
Insert into PAIS (PAIS_ID,NOMBRE) values ('FLK','Islas Malvinas');
Insert into PAIS (PAIS_ID,NOMBRE) values ('MNP','Islas Marianas del Norte');
Insert into PAIS (PAIS_ID,NOMBRE) values ('MHL','Islas Marshall');
Insert into PAIS (PAIS_ID,NOMBRE) values ('PCN','Islas Pitcairn');
Insert into PAIS (PAIS_ID,NOMBRE) values ('SLB','Islas Salomón');
Insert into PAIS (PAIS_ID,NOMBRE) values ('TCA','Islas Turcas y Caicos');
Insert into PAIS (PAIS_ID,NOMBRE) values ('UMI','Islas Ultramarinas Menores de Estados Unidos');
Insert into PAIS (PAIS_ID,NOMBRE) values ('VG','Islas Vírgenes Británicas');
Insert into PAIS (PAIS_ID,NOMBRE) values ('VIR','Islas Vírgenes de los Estados Unidos');
Insert into PAIS (PAIS_ID,NOMBRE) values ('ISR','Israel');
Insert into PAIS (PAIS_ID,NOMBRE) values ('ITA','Italia');
Insert into PAIS (PAIS_ID,NOMBRE) values ('JAM','Jamaica');
Insert into PAIS (PAIS_ID,NOMBRE) values ('JPN','Japón');
Insert into PAIS (PAIS_ID,NOMBRE) values ('JEY','Jersey');
Insert into PAIS (PAIS_ID,NOMBRE) values ('JOR','Jordania');
Insert into PAIS (PAIS_ID,NOMBRE) values ('KAZ','Kazajistán');
Insert into PAIS (PAIS_ID,NOMBRE) values ('KEN','Kenia');
Insert into PAIS (PAIS_ID,NOMBRE) values ('KGZ','Kirgizstán');
Insert into PAIS (PAIS_ID,NOMBRE) values ('KIR','Kiribati');
Insert into PAIS (PAIS_ID,NOMBRE) values ('KWT','Kuwait');
Insert into PAIS (PAIS_ID,NOMBRE) values ('LBN','Líbano');
Insert into PAIS (PAIS_ID,NOMBRE) values ('LAO','Laos');
Insert into PAIS (PAIS_ID,NOMBRE) values ('LSO','Lesoto');
Insert into PAIS (PAIS_ID,NOMBRE) values ('LVA','Letonia');
Insert into PAIS (PAIS_ID,NOMBRE) values ('LBR','Liberia');
Insert into PAIS (PAIS_ID,NOMBRE) values ('LBY','Libia');
Insert into PAIS (PAIS_ID,NOMBRE) values ('LIE','Liechtenstein');
Insert into PAIS (PAIS_ID,NOMBRE) values ('LTU','Lituania');
Insert into PAIS (PAIS_ID,NOMBRE) values ('LUX','Luxemburgo');
Insert into PAIS (PAIS_ID,NOMBRE) values ('MEX','México');
Insert into PAIS (PAIS_ID,NOMBRE) values ('MCO','Mónaco');
Insert into PAIS (PAIS_ID,NOMBRE) values ('MAC','Macao');
Insert into PAIS (PAIS_ID,NOMBRE) values ('MKD','Macedônia');
Insert into PAIS (PAIS_ID,NOMBRE) values ('MDG','Madagascar');
Insert into PAIS (PAIS_ID,NOMBRE) values ('MYS','Malasia');
Insert into PAIS (PAIS_ID,NOMBRE) values ('MWI','Malawi');
Insert into PAIS (PAIS_ID,NOMBRE) values ('MLI','Mali');
Insert into PAIS (PAIS_ID,NOMBRE) values ('MLT','Malta');
Insert into PAIS (PAIS_ID,NOMBRE) values ('MAR','Marruecos');
Insert into PAIS (PAIS_ID,NOMBRE) values ('MTQ','Martinica');
Insert into PAIS (PAIS_ID,NOMBRE) values ('MUS','Mauricio');
Insert into PAIS (PAIS_ID,NOMBRE) values ('MRT','Mauritania');
Insert into PAIS (PAIS_ID,NOMBRE) values ('MYT','Mayotte');
Insert into PAIS (PAIS_ID,NOMBRE) values ('FSM','Micronesia');
Insert into PAIS (PAIS_ID,NOMBRE) values ('MDA','Moldavia');
Insert into PAIS (PAIS_ID,NOMBRE) values ('MNG','Mongolia');
Insert into PAIS (PAIS_ID,NOMBRE) values ('MNE','Montenegro');
Insert into PAIS (PAIS_ID,NOMBRE) values ('MSR','Montserrat');
Insert into PAIS (PAIS_ID,NOMBRE) values ('MOZ','Mozambique');
Insert into PAIS (PAIS_ID,NOMBRE) values ('NAM','Namibia');
Insert into PAIS (PAIS_ID,NOMBRE) values ('NRU','Nauru');
Insert into PAIS (PAIS_ID,NOMBRE) values ('NPL','Nepal');
Insert into PAIS (PAIS_ID,NOMBRE) values ('NIC','Nicaragua');
Insert into PAIS (PAIS_ID,NOMBRE) values ('NER','Niger');
Insert into PAIS (PAIS_ID,NOMBRE) values ('NGA','Nigeria');
Insert into PAIS (PAIS_ID,NOMBRE) values ('NIU','Niue');
Insert into PAIS (PAIS_ID,NOMBRE) values ('NOR','Noruega');
Insert into PAIS (PAIS_ID,NOMBRE) values ('NCL','Nueva Caledonia');
Insert into PAIS (PAIS_ID,NOMBRE) values ('NZL','Nueva Zelanda');
Insert into PAIS (PAIS_ID,NOMBRE) values ('OMN','Omán');
Insert into PAIS (PAIS_ID,NOMBRE) values ('NLD','Países Bajos');
Insert into PAIS (PAIS_ID,NOMBRE) values ('PAK','Pakistán');
Insert into PAIS (PAIS_ID,NOMBRE) values ('PLW','Palau');
Insert into PAIS (PAIS_ID,NOMBRE) values ('PSE','Palestina');
Insert into PAIS (PAIS_ID,NOMBRE) values ('PAN','Panamá');
Insert into PAIS (PAIS_ID,NOMBRE) values ('PNG','Papúa Nueva Guinea');
Insert into PAIS (PAIS_ID,NOMBRE) values ('PRY','Paraguay');
Insert into PAIS (PAIS_ID,NOMBRE) values ('PER','Perú');
Insert into PAIS (PAIS_ID,NOMBRE) values ('POL','Polonia');
Insert into PAIS (PAIS_ID,NOMBRE) values ('PRT','Portugal');
Insert into PAIS (PAIS_ID,NOMBRE) values ('PRI','Puerto Rico');
Insert into PAIS (PAIS_ID,NOMBRE) values ('QAT','Qatar');
Insert into PAIS (PAIS_ID,NOMBRE) values ('GBR','Reino Unido');
Insert into PAIS (PAIS_ID,NOMBRE) values ('CAF','República Centroafricana');
Insert into PAIS (PAIS_ID,NOMBRE) values ('CZE','República Checa');
Insert into PAIS (PAIS_ID,NOMBRE) values ('DOM','República Dominicana');
Insert into PAIS (PAIS_ID,NOMBRE) values ('REU','Reunión');
Insert into PAIS (PAIS_ID,NOMBRE) values ('RWA','Ruanda');
Insert into PAIS (PAIS_ID,NOMBRE) values ('ROU','Rumanía');
Insert into PAIS (PAIS_ID,NOMBRE) values ('RUS','Rusia');
Insert into PAIS (PAIS_ID,NOMBRE) values ('ESH','Sahara Occidental');
Insert into PAIS (PAIS_ID,NOMBRE) values ('WSM','Samoa');
Insert into PAIS (PAIS_ID,NOMBRE) values ('ASM','Samoa Americana');
Insert into PAIS (PAIS_ID,NOMBRE) values ('BLM','San Bartolomé');
Insert into PAIS (PAIS_ID,NOMBRE) values ('KNA','San Cristóbal y Nieves');
Insert into PAIS (PAIS_ID,NOMBRE) values ('SMR','San Marino');
Insert into PAIS (PAIS_ID,NOMBRE) values ('MAF','San Martín (Francia)');
Insert into PAIS (PAIS_ID,NOMBRE) values ('SPM','San Pedro y Miquelón');
Insert into PAIS (PAIS_ID,NOMBRE) values ('VCT','San Vicente y las Granadinas');
Insert into PAIS (PAIS_ID,NOMBRE) values ('SHN','Santa Elena');
Insert into PAIS (PAIS_ID,NOMBRE) values ('LCA','Santa Lucía');
Insert into PAIS (PAIS_ID,NOMBRE) values ('STP','Santo Tomé y Príncipe');
Insert into PAIS (PAIS_ID,NOMBRE) values ('SEN','Senegal');
Insert into PAIS (PAIS_ID,NOMBRE) values ('SRB','Serbia');
Insert into PAIS (PAIS_ID,NOMBRE) values ('SYC','Seychelles');
Insert into PAIS (PAIS_ID,NOMBRE) values ('SLE','Sierra Leona');
Insert into PAIS (PAIS_ID,NOMBRE) values ('SGP','Singapur');
Insert into PAIS (PAIS_ID,NOMBRE) values ('SYR','Siria');
Insert into PAIS (PAIS_ID,NOMBRE) values ('SOM','Somalia');
Insert into PAIS (PAIS_ID,NOMBRE) values ('LKA','Sri lanka');
Insert into PAIS (PAIS_ID,NOMBRE) values ('ZAF','Sudáfrica');
Insert into PAIS (PAIS_ID,NOMBRE) values ('SDN','Sudán');
Insert into PAIS (PAIS_ID,NOMBRE) values ('SWE','Suecia');
Insert into PAIS (PAIS_ID,NOMBRE) values ('CHE','Suiza');
Insert into PAIS (PAIS_ID,NOMBRE) values ('SUR','Surinám');
Insert into PAIS (PAIS_ID,NOMBRE) values ('SJM','Svalbard y Jan Mayen');
Insert into PAIS (PAIS_ID,NOMBRE) values ('SWZ','Swazilandia');
Insert into PAIS (PAIS_ID,NOMBRE) values ('TJK','Tadjikistán');
Insert into PAIS (PAIS_ID,NOMBRE) values ('THA','Tailandia');
Insert into PAIS (PAIS_ID,NOMBRE) values ('TWN','Taiwán');
Insert into PAIS (PAIS_ID,NOMBRE) values ('TZA','Tanzania');
Insert into PAIS (PAIS_ID,NOMBRE) values ('IOT','Territorio Británico del Océano Índico');
Insert into PAIS (PAIS_ID,NOMBRE) values ('ATF','Territorios Australes y Antárticas Franceses');
Insert into PAIS (PAIS_ID,NOMBRE) values ('TLS','Timor Oriental');
Insert into PAIS (PAIS_ID,NOMBRE) values ('TGO','Togo');
Insert into PAIS (PAIS_ID,NOMBRE) values ('TKL','Tokelau');
Insert into PAIS (PAIS_ID,NOMBRE) values ('TON','Tonga');
Insert into PAIS (PAIS_ID,NOMBRE) values ('TTO','Trinidad y Tobago');
Insert into PAIS (PAIS_ID,NOMBRE) values ('TUN','Tunez');
Insert into PAIS (PAIS_ID,NOMBRE) values ('TKM','Turkmenistán');
Insert into PAIS (PAIS_ID,NOMBRE) values ('TUR','Turquía');
Insert into PAIS (PAIS_ID,NOMBRE) values ('TUV','Tuvalu');
Insert into PAIS (PAIS_ID,NOMBRE) values ('UKR','Ucrania');
Insert into PAIS (PAIS_ID,NOMBRE) values ('UGA','Uganda');
Insert into PAIS (PAIS_ID,NOMBRE) values ('URY','Uruguay');
Insert into PAIS (PAIS_ID,NOMBRE) values ('UZB','Uzbekistán');
Insert into PAIS (PAIS_ID,NOMBRE) values ('VUT','Vanuatu');
Insert into PAIS (PAIS_ID,NOMBRE) values ('VEN','Venezuela');
Insert into PAIS (PAIS_ID,NOMBRE) values ('VNM','Vietnam');
Insert into PAIS (PAIS_ID,NOMBRE) values ('WLF','Wallis y Futuna');
Insert into PAIS (PAIS_ID,NOMBRE) values ('YEM','Yemen');
Insert into PAIS (PAIS_ID,NOMBRE) values ('DJI','Yibuti');
Insert into PAIS (PAIS_ID,NOMBRE) values ('ZMB','Zambia');
Insert into PAIS (PAIS_ID,NOMBRE) values ('ZWE','Zimbabue');
Insert into PAIS (PAIS_ID,NOMBRE) values ('AFG','Afganistán');
Insert into PAIS (PAIS_ID,NOMBRE) values ('ALB','Albania');
Insert into PAIS (PAIS_ID,NOMBRE) values ('DEU','Alemania');
Insert into PAIS (PAIS_ID,NOMBRE) values ('DZA','Algeria');
Insert into PAIS (PAIS_ID,NOMBRE) values ('AND','Andorra');
Insert into PAIS (PAIS_ID,NOMBRE) values ('AGO','Angola');
Insert into PAIS (PAIS_ID,NOMBRE) values ('AIA','Anguila');
Insert into PAIS (PAIS_ID,NOMBRE) values ('ATA','Antártida');
Insert into PAIS (PAIS_ID,NOMBRE) values ('ATG','Antigua y Barbuda');
Insert into PAIS (PAIS_ID,NOMBRE) values ('ANT','Antillas Neerlandesas');
Insert into PAIS (PAIS_ID,NOMBRE) values ('SAU','Arabia Saudita');
Insert into PAIS (PAIS_ID,NOMBRE) values ('ARG','Argentina');
Insert into PAIS (PAIS_ID,NOMBRE) values ('ARM','Armenia');
Insert into PAIS (PAIS_ID,NOMBRE) values ('ABW','Aruba');
Insert into PAIS (PAIS_ID,NOMBRE) values ('AUS','Australia');
Insert into PAIS (PAIS_ID,NOMBRE) values ('AUT','Austria');
Insert into PAIS (PAIS_ID,NOMBRE) values ('AZE','Azerbayán');
Insert into PAIS (PAIS_ID,NOMBRE) values ('BEL','Bélgica');
Insert into PAIS (PAIS_ID,NOMBRE) values ('BHS','Bahamas');
Insert into PAIS (PAIS_ID,NOMBRE) values ('BHR','Bahrein');
Insert into PAIS (PAIS_ID,NOMBRE) values ('BGD','Bangladesh');
Insert into PAIS (PAIS_ID,NOMBRE) values ('BRB','Barbados');
Insert into PAIS (PAIS_ID,NOMBRE) values ('BLZ','Belice');
Insert into PAIS (PAIS_ID,NOMBRE) values ('BEN','Benín');
Insert into PAIS (PAIS_ID,NOMBRE) values ('BTN','Bhután');
Insert into PAIS (PAIS_ID,NOMBRE) values ('BLR','Bielorrusia');
Insert into PAIS (PAIS_ID,NOMBRE) values ('MMR','Birmania');
Insert into PAIS (PAIS_ID,NOMBRE) values ('BOL','Bolivia');
Insert into PAIS (PAIS_ID,NOMBRE) values ('BIH','Bosnia y Herzegovina');
Insert into PAIS (PAIS_ID,NOMBRE) values ('BWA','Botsuana');
Insert into PAIS (PAIS_ID,NOMBRE) values ('BRA','Brasil');
Insert into PAIS (PAIS_ID,NOMBRE) values ('BRN','Brunéi');
commit;
